Main s1 p1
teamdigitale/dati-semantic-frontend pull request #236
Opened 2022-10-21 14:56 UTC by DoomRock88

2022-10-21 14:59 UTC, DoomRock88 commented
aggiunte pagine di errore, fix swagger-ui mouse hover, cambio di testi nelle sezioni "il progetto" e "domande frequenti"

2022-10-21 15:02 UTC, ioggstream requested changes
@DoomRock88 Vedi i commenti sul package.json

Il resto sono per @Clou-dia

2022-10-21 15:02 UTC, ioggstream commented on src/components/search/SearchPage/SearchPage.js
> +        message="Ci scusiamo per il disagio, riprovare fra qualche minuto"
@Clou-dia i nuovi messaggi di errore sono questi? Conviene suggerire un modo per aprire un issue già da qui?

2022-10-21 15:02 UTC, ioggstream commented on src/components/static-content/project/ProjectBody/ProjectBody.js
> +          <p>
@Clou-dia confermi?

2022-10-21 15:11 UTC, ioggstream commented on src/components/common/IntroSection/IntroSection.js
> +                {/* <p>{window.location.href}</p> */}
Se una riga di codice non serve, alla fine va eliminata https://en.wikipedia.org/wiki/You_aren%27t_gonna_need_it

2022-10-21 18:34 UTC, ioggstream commented on src/components/layout/ErrorPage/ErrorPage.js
> +      {/* <div className={styles.abstract}>{message}</div> */}
@DoomRock88 perché questo commento?

2022-10-21 18:34 UTC, ioggstream commented on src/components/layout/NotFound/NotFound.js
> +      {/* <div className={styles.abstract}>{message}</div> */}
Questa parte commentata, serve?

2022-10-24 09:00 UTC, Clou-dia commented
Modifiche al front-end verificate

- [ ] aggiunte pagine di errore --> ok, check solo su img. di _nessun risultato_ che viene tagliata
- [ ] fix swagger-ui mouse hover
- [ ] cambio di testi nelle sezioni "il progetto" e "domande frequenti" --> ok ma prima di mandare online aggiungere indice di pagina

2022-10-24 09:02 UTC, Clou-dia commented on src/components/search/SearchPage/SearchPage.js
> +        message="Ci scusiamo per il disagio, riprovare fra qualche minuto"
no questa sarebbe una pagina rotta. 
l'aprire issue lo inserire a piè di pagina dove ora abbiamo il contribuisci

2022-10-24 09:03 UTC, Clou-dia commented on src/components/static-content/project/ProjectBody/ProjectBody.js
> +          <p>
confermo nuovi testi ok

2022-10-24 09:52 UTC, ioggstream approved these changes
LGTM con @Clou-dia per testare le modifiche

2022-10-24 09:52 UTC, merged