Aggiunta BreadCrumbs
teamdigitale/dati-semantic-frontend pull request #250
Opened 2022-10-28 15:41 UTC by DoomRock88

## Inserito breadCrunbs nelle pagine

This PR does:

1. Inserito breadCrunbs nelle pagine di tutto il progetto
2. 

Fixes #xxx

## Checklist

- [ ] I followed the [CONTRIBUTING](../CONTRIBUTING.md) guidelines.
- [ ] I updated the documentation.

2022-10-28 18:13 UTC, ioggstream requested changes
See requested changes,
R

2022-10-28 18:13 UTC, ioggstream commented on .env
> +API_URL=http://localhost:8080
Cosa fa questa modifica?

2022-10-28 18:13 UTC, ioggstream commented on src/services/BreadCrumbsConst.js
> +  ESPLORA: ESPLORA,
I nomi delle variabili possiamo tenerli in inglese? I testi invece sono giusti in italiano.

2022-10-28 20:37 UTC, DoomRock88 commented
Hai ragione modifico tutto appena possibile 
--
Inviato da Libero Mail per Android venerdì, 28 ottobre 2022, 08:13PM +02:00 da Roberto Polli  ***@***.*** :

***@***.*** requested changes on this pull request.
>See requested changes,
>R
>----------------------------------------------------------------------
>In  .env :
> @@ -1,4 +1,4 @@
>-API_URL=
>+API_URL=http://localhost:8080
>
>Cosa fa questa modifica?
>----------------------------------------------------------------------
>In  src/services/BreadCrumbsConst.js :
> +];
>+export const RICERCA = [
>+  { label: "Home", link: "/", id: 6 },
>+  { label: "Ricerca nel catalogo", link: "", id: 7 },
>+];
>+export const RICERCADETTAGLIO = [
>+  { label: "Home", link: "/", id: 8 },
>+  { label: "Ricerca nel catalogo", link: "back", id: 9 },
>+  { label: "Dettaglio asset", link: "", id: 10 },
>+];
>+export const PRIVACY = [
>+  { label: "Home", link: "/", id: 11 },
>+  { label: "Privacy policy", link: "", id: 12 },
>+];
>+export const BREADCRUMBS = {
>+  ESPLORA: ESPLORA,
>
>I nomi delle variabili possiamo tenerli in inglese? I testi invece sono giusti in italiano.
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>You are receiving this because you authored the thread. Message ID:  @ github . com>

2022-11-02 11:54 UTC, closed without merging

2022-11-02 11:54 UTC, DoomRock88 commented
create a new pull request with bugfix